default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dat_depot_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: dat_depot_test
  host: localhost
  port: 5432

production:
  <<: *default
  database: dat_depot_production
  username: dat_depot
  password: <%= ENV['DAT_DEPOT_DATABASE_PASSWORD'] %>
